name: marimba
description: Marimba App made in Flutter.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  just_audio: ^0.9.29
  

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  android: true
  ios: true 

flutter:
  uses-material-design: true

  assets:
    - assets/


